//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConfigAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1.0 的本地化字符串。
        /// </summary>
        internal static string AppVs {
            get {
                return ResourceManager.GetString("AppVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string DownIP {
            get {
                return ResourceManager.GetString("DownIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6666 的本地化字符串。
        /// </summary>
        internal static string DownPort {
            get {
                return ResourceManager.GetString("DownPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string HallIP {
            get {
                return ResourceManager.GetString("HallIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5656 的本地化字符串。
        /// </summary>
        internal static string HallPort {
            get {
                return ResourceManager.GetString("HallPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string LoginIP {
            get {
                return ResourceManager.GetString("LoginIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4646 的本地化字符串。
        /// </summary>
        internal static string LoginPort {
            get {
                return ResourceManager.GetString("LoginPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;RSAKeyValue&gt;&lt;Modulus&gt;s2DfHwx3Liot/yyJFxkerQNdUR082Dcyy1O65SEo6XlSYe0FQtuHKKwTMGaR0Yk0NeHGjq+1XYzJ9r+9GTFlm/ObjVzpyoRnExB05lWSwBAsOGr+5EWhWze8gi7BRyi26iPDspDuY71ZzgYZyxB6zfiSF8EJTQRbANgrSdDJfJk=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;4tZ96/U0qyrY/+fD03tSe8gkZfcUZzS5peyUDL/3wgfLjBujGXWhY6/7DJl7ZJgznFiJrYjHYqYnBsOoZKpSPQ==&lt;/P&gt;&lt;Q&gt;ynBugnhxYmEZAlW8ipGGjeCiC3JZBOc02wwM3TpXFgqR2ZycCkY9bMjMm1aWM4M5tiP5tnFyovQ54FOJecsFjQ==&lt;/Q&gt;&lt;DP&gt;S6GObIzeGa/4mCJTRYDZuJG7qQ+fiuWmfG8L0dBzsArfUACq+cMho1Y6kzHdVWX110wh4202ZWrWmkfELoQnVQ==&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 127.0.0.1 的本地化字符串。
        /// </summary>
        internal static string UpdateIP {
            get {
                return ResourceManager.GetString("UpdateIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdatePath 的本地化字符串。
        /// </summary>
        internal static string UpdatePath {
            get {
                return ResourceManager.GetString("UpdatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7676 的本地化字符串。
        /// </summary>
        internal static string UpdatePort {
            get {
                return ResourceManager.GetString("UpdatePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20130923 的本地化字符串。
        /// </summary>
        internal static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
    }
}
